### ISSUE TITLE
Forks processing

### ISSUE THREAD

**Issue by catena2w** [ergoplatform/explorer-back#11]
In case of forks, explorer should show the block from the main chain. It can be detected in as a first id in 
`http://209.97.136.204:9052/blocks/at/<height>` request. E.g. http://209.97.136.204:9052/blocks/at/5874 returns 2 blocks: 
```
[
  "02c7db941cec8f27273c557722c09071f7d2dd58af5ae07160e904eb19d9b247",
  "01cb964ecee813d18e9461702137237014cf4553069368caaf2ba249bb7e234b"
]
```
where 02c7db941cec8f27273c557722c09071f7d2dd58af5ae07160e904eb19d9b247 is the block from the main chain and should be shown in explorer. Right now block 01cb964ecee813d18e9461702137237014cf4553069368caaf2ba249bb7e234b is shown at height 5874

**Comment by daron666** [comment]
Currently we are processing all the blocks from node, even if they are in fork.
