### ISSUE TITLE
api improvements for wallets and analysis

### ISSUE THREAD

**Issue by ra3dnr** [ergoplatform/explorer-back#138]
Few features that will be helpful for wallets and analysis
1. GET /blocks should return blocks sorted descending by height
starting from the latest block by default. This is more frequent use case than
ascending from genesis
2. A method which returns list of outputs (boxes) belonging to address is needed.
It is also convenient to have id of transaction which created the box together
with box itself. Maybe return unspent/spent/all boxes depending on parameters
(together with spentTransactionId - as happens with transactions now)
3. Would be nice if fields in JSON for transactions and boxes were exactly the
same (by names and content) as corresponding ones returned by Ergo node. 
This would reduce overhead in parsing, signature checks, assets counting etc.
4. Additionally it would be nice to have block id together with returned
transaction. spentTransactionId is helpful, do not remove it please.
5. It is good to have an option of requesting block by height
6. /info should also contain current height

**Comment by oskin1** [comment]
Closed via #139
