### ISSUE TITLE
[ Chart ] Hashrate distribution

### ISSUE THREAD

**Issue by appbak3r** [ergoplatform/explorer-back#51]
https://app.swaggerhub.com/apis/BlockchainInstitute/blockchain-explorer/1.0.0#/charts/get_charts_hash_rate_distribution

**Comment by daron666** [comment]
@appbak3r How many `Top Miners` should be presented on this chart?

**Comment by appbak3r** [comment]
@catena2w

**Comment by catena2w** [comment]
@appbak3r what is the mininal share, that will be visible on a graph?
@daron666 I think you should collect all the miners during the last day and return those, whose share is higher than some threshold (e. G. 1%) remaining miners should be shown aggregated as 'others'

**Comment by appbak3r** [comment]
I think not less than 1%

**Comment by daron666** [comment]
Ok! Thanks for clarification.
