### ISSUE TITLE
Check explorer back API conformity with spec

### ISSUE THREAD

**Issue by mike-aksarin** [ergoplatform/explorer-back#61]
Please use API verification tool from Ergo to check Ergo explorer back API conformity with Open API spec.

Open API specification could be downloaded here: https://app.swaggerhub.com/apis/BlockchainInstitute/blockchain-explorer/1.0.0/

Explorer back is deployed here:
https://api.testnet.ergoplatform.com

**Comment by andyceo** [comment]
I created utility for this: https://hub.docker.com/r/andyceo/openapi-checker/

See example parameters.yml for Ergo node OpenAPI testing: https://github.com/ergoplatform/ansible/blob/master/files/parameters.yaml

For testing your OpenAPI spec and responses do something like this:

```
sudo docker run --rm andyceo/openapi-checker https://app.swaggerhub.com/apiproxy/schema/file/BlockchainInstitute/blockchain-explorer/1.0.0/swagger.yaml --api https://api-testnet.ergoplatform.com
```

You must create your own parameters.yml to check parametrized endpoints and pass file to utility. See docpage  https://hub.docker.com/r/andyceo/openapi-checker/ for details.
