### ISSUE TITLE
Duplicate output

### ISSUE THREAD

**Issue by catena2w** [ergoplatform/explorer-back#68]
There are 3 outputs shown in explorer in transaction https://testnet.ergoplatform.com/ru/transactions/c5fd4bf7b230978b258844d022846b80a29e9b9b026bfe0716f301abac008f5d, while original transaction have only 2 outputs http://88.198.13.202:9052/blocks/006761710e219d8b75262395e1555df7c647642ae81d9b3e9d39522b92d5b9de/transactions

May relate to https://github.com/ergoplatform/explorer-back/issues/67

**Comment by daron666** [comment]
Found a reason - dup came from fork.

**Comment by daron666** [comment]
Need deeper investigation how properly avoid such situations, but for now there won't be dups.
