### ISSUE TITLE
Stats page

### ISSUE THREAD

**Issue by catena2w** [ergoplatform/explorer-back#77]
Please check values in stats page and provide equations, how did you calculated them

**Comment by daron666** [comment]
@catena2w 

First of all I retrieve the list of block infos for the last 24 hours, lets call it `List`

`Blocks Mined = List.length`
`Average Mining Time = List.map(_.miningTime) / List.length`
`Total Coins Mined = List.map(_.minerReward).sum`
`Transactions Count = List.map(_.txsCount).sum`
`Total Transaction Fees = List.map(_.blockFee).sum`
`Total Output Value = Just sum of all unspent outputs for the last 24h`
`Total Miners Revenue = List.map(v => v.minerReward + v.blockFee).sum`
`% Earned From Transaction Fees = totalFees / (minersReward + totalFees)`
`% Of Transaction Volume = minersReward / totalCoinsInBlock`
`Cost per Transaction = MinersRevenue / TxsCount`
`Difficulty = Difficulty of a last block`
`Hasrate = Sume of all blocks for 24h / Seconds in 24h`
